create table if not exists helper_updates (
  id bigint generated by default as identity primary key,
  version text not null,
  platform text not null,
  download_url text not null,
  checksum text,
  release_notes text,
  inserted_at timestamptz default now()
);

create index if not exists helper_updates_version_idx
  on helper_updates (version desc);

